# Generated by Django 5.2 on 2025-05-03 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('chat', '0002_class_chatmessage_class_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='appointment.appointment'),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
