# Generated by Django 5.2 on 2025-05-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_class_obj_delete_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='class_obj',
            new_name='appointment_obj',
        ),
    ]
