# Generated by Django 5.2 on 2025-05-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_date_of_birth_patient_dob_and_more'),
        ('appointment', '0002_appointmentrequest_doctor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointmentrequest',
            unique_together={('patient', 'appointment_obj', 'doctor')},
        ),
    ]
