# Generated by Django 5.2 on 2025-05-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointmentrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
