# Generated by Django 5.2 on 2025-05-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_appointmentrequest_appointment_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='appointment_number',
        ),
    ]
