# Generated by Django 5.2.1 on 2025-05-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_remove_appointmentrequest_appointment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.FileField(upload_to='appointment_descriptions/'),
        ),
    ]
