# Generated by Django 5.2.1 on 2025-05-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_appointment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='description',
        ),
        migrations.AddField(
            model_name='appointment',
            name='description_file',
            field=models.FileField(blank=True, null=True, upload_to='appointment_descriptions/'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='description_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
