# Generated by Django 5.2.1 on 2025-05-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_remove_appointment_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='description_file',
            field=models.FileField(blank=True, null=True, upload_to='appointment_descriptions/'),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='description_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
