# Generated by Django 5.2.1 on 2025-05-24 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_doctor_photo_alter_patient_photo_and_more'),
        ('appointment', '0008_appointmentrequest_description_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to='api.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='api.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='enrolled_patients',
            field=models.ManyToManyField(blank=True, related_name='enrolled_appointments', to='api.patient'),
        ),
    ]
