# Generated by Django 5.2.1 on 2025-05-25 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_appointment_patient_alter_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='description_text',
        ),
        migrations.RemoveField(
            model_name='appointmentrequest',
            name='description_text',
        ),
    ]
