# Generated by Django 5.2.1 on 2025-05-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_remove_appointment_description_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='schedule',
            field=models.TextField(default=''),
        ),
    ]
