# Generated by Django 5.2 on 2025-04-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='Confirmpass',
        ),
    ]
