# Generated by Django 5.2 on 2025-04-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_doctor_confirmpass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone_number',
        ),
    ]
