# Generated by Django 5.2 on 2025-04-28 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_doctor_date_of_birth_doctor_introduction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Confirmpass',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='localisation',
        ),
    ]
