# Generated by Django 5.2 on 2025-04-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='introduction',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='fullname',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
