# Generated by Django 5.2 on 2025-05-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_introduction_doctor_about_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='fullname',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('PATIENT', 'Patient')], default='student', max_length=50),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
