# Generated by Django 5.2 on 2025-05-03 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_date_of_birth_patient_dob_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
