# Generated by Django 5.2.1 on 2025-05-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_doctor_photo_alter_patient_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='deplome',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
